version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hyphae-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f3wgmkhe3hqn"
s3_prefix = "hyphae-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
