version: "3"
services:
  broker:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    networks:
      - localnet
    ports:
      - "1883:1883"
  node:
    depends_on:
      - broker
    image: hub-server
    user: "0"
    networks:
      - localnet
    ports:
      - "1880:1880"
networks:
  localnet:
